/**
 * Equivalencias entre el nombre que usa el comprador en la lista de temporadas y
 * el nombre de la tela que arma la app desde el ERP (dato de negocio editable).
 *
 * Solo hace falta para los nombres que NO coinciden exacto (los exactos se cruzan
 * solos). Un nombre de la lista puede cubrir varias telas de la app
 * ("FLANNEL LUMINOSO" → liso y DSN). Lo que no está acá ni coincide exacto queda
 * "sin asignar" y se completa desde la vista Temporadas.
 *
 * Propuestas 08-10-2026 cruzando la lista con los exports de sep-2026. Quedaron
 * afuera, por dudosas, y se asignan a mano: ALGODON CON LYCRA IMPORTADO,
 * BENGALINA DENIM, CAMISACO CON PIEL, CUERITO FRISADO, LANILLA CASHMIRE BRUSH PRINT,
 * MICROTUL (SOLO COLORES VERANO), MORLEY VISCOSA B FINO / B MINI,
 * PARACHUTTE METALIZADO, POPLIN RAYON CON LYCRA y WAFFLE RAYADO.
 */
export const ALIAS_TEMPORADAS: Readonly<Record<string, readonly string[]>> = {
  '4 WAYS': ['4 WAY'],
  'ANGIE GLITTER': ['MICRO MORLEY ANGIE GLITTER'],
  'BIZU BIZU ACID': ['BIZU ACID'],
  'BIZU BIZU ANIMAL': ['BIZU ANIMAL'],
  'BIZU BIZU COSMIC': ['BIZU COSMIC'],
  'BRODERY DE PLANO': ['BRODERY PLANO'],
  BRUSELLAS: ['BRUSELAS'],
  'CEY PUFF DSN': ['CEY PUFF'],
  'CHARO FOIL': ['MICROFIBRA CON LYCRA CHARO FOIL'],
  'CORDERITO BIFAZ PRINT': ['CORDERITO BIFAZ DSN'],
  'COTTON POPLIN SPX': ['COTTON POPLIN SPANDEX'],
  'CROCHET DE PUNTO': ['CROCHET'],
  'DARLON PRINT': ['DARLON DSN'],
  'DENIM JQD': ['DENIM JACQUARD'],
  'FLANNEL LUMINOSO': ['FLANEL LUMINOSO', 'FLANEL LUMINOSO DSN'],
  'FRISA POLY': ['FRISA POLYESTER'],
  'LANILLA ANGORA COSY': ['LAILLA ANGORA COSY'], // typo del ERP
  'LANILLA BRUSH LISA': ['LANILLA BRUSH'],
  'LANILLA JAQUARD BRUSH': ['LANILLA JACQUARD'],
  'LANILLA LONDRES MORLEY': ['LANILLA LON MORLEY'],
  'LANILLA MELLOW': ['LANILLA MELLOW BRUSH'],
  'LANILLA WAFFLE BRUSH': ['LANILLA WAFFLE'],
  'LANILLA WAFFLE MINI BRUSH': ['LANILLA WAFFLE MINI'],
  'LENTEJUELA PRINT': ['LENTEJUELA DSN'],
  'LINO PANTALONERO RIGIDO': ['LINO PANTALONERO'],
  'MICROFIBRA CHARO': ['MICROFIBRA CON LYCRA CHARO'],
  'MICROFIBRA ENGOMADA': ['MICROFIBRA ENGOMADA MATTE', 'MICROFIBRA ENGOMADA METALIZADA'],
  'MICROMORLEY ANGIE': ['MICRO MORLEY ANGIE'],
  'MICROMORLEY BRITNEY': ['MORLEY BRITNEY'],
  'MICROMORLEY FOIL': ['MICRO MORLEY FOIL'],
  'MICROMORLEY NICKY': ['MICRO MORLEY NICKY'],
  'MICROMORLEY RAYADO': ['MICRO MORLEY RAYADO', 'MICRO MORLEY RAYADO DSN'],
  'MICROTUL CON FLOCK': ['MICROTUL FLOCK'],
  'MICROTUL CON STRASS': ['MICROTUL STRASS'],
  'MODAL ESTAMPADO KIDS': ['MODAL SOFT NIÑXS'],
  'MODAL SOFT PRINT': ['MODAL SOFT DSN'],
  'MORLEY BRUSH PRINT': ['MORLEY BRUSH DSN'],
  'MORLEY DIESEL BRUSHED': ['MORLEY DIESEL BRUSH'],
  'MORLEY PRINT': ['MORLEY DSN'],
  'MORLEY VISCOSA (ANCHO, FINO, SIENA)': ['MORLEY BASTON ANCHO', 'MORLEY BASTON FINO', 'MORLEY BASTON SIENNA'],
  'PAÑO BOUCLE ESTAMPADO': ['PAÑO DE PUNTO BOUCLE DSN'],
  'PAÑO BOUCLE LISO': ['PAÑO DE PUNTO BOUCLE'],
  PARACHUTTE: ['PARACHUTE'],
  'POPLIN ESTAMPADO': ['POPLIN DSN'],
  'POPLIN LISO': ['POPLIN'],
  'RETRO FRIZADO': ['RETRO FRISADO', 'RETRO FRIZADO N'],
  'RIBB GIGI': ['RIB GIGI'],
  'RIBB ONIX': ['RIB ONIX'],
  'SATEN CON SPANDEX (PLANO)': ['SATEN SPANDEX'],
  'SCUBA CREPPE': ['SCUBA CREP'],
  'TERMOPOLAR JQD': ['TERMOPOLAR JACQUARD'],
  'TERMOPOLAR LISO': ['TERMOPOLAR'],
  'TIMBERLAND LISO': ['TIMBERLAND'], // liso y estampado se fusionaron en una tela (FUSIONES_TELAS)
  'TIMBERLAND PRINT': ['TIMBERLAND'],
  'TRENCH (WATERPROOF)': ['TRENCH'],
};
