/**
 * Lista base de temporadas por tela (dato de negocio editable).
 *
 * Sembrada desde `TEMPORADAS DE ARTICULOS.xlsx` (hoja LISTA, 08-10-2026, 191 telas).
 * Los nombres son los del comprador; no siempre coinciden con los del ERP: las
 * equivalencias viven en `aliasTemporadas.ts`. Desde la vista Temporadas se puede
 * cargar una lista nueva (.xlsx) o corregir tela por tela sin tocar este archivo.
 */
import type { Temporada } from '@/shared/tipos/temporada';

/** Una fila de la lista: nombre de tela (como lo escribe el comprador) y su temporada. */
export interface EntradaTemporada {
  readonly nombre: string;
  readonly temporada: Temporada;
}

const porTemporada: Record<Temporada, readonly string[]> = {
  VERANO: [
    'ALGODON RUSTICO', 'BABY COTTON', 'BELLA', 'BRODERY DE PLANO', 'BRUSELLAS', 'CEY', 'CEY CUBA',
    'CEY DE PUNTO', 'CEY LINO', 'CEY PUFF DSN', 'CEY RAYADO', 'CEY TWILL', 'CEY VINTAGE',
    'CREP VISCOSA', 'CROCHET DE PUNTO', 'CROCHET LISBOA', 'CROCHET RIO', 'HAWAII', 'LINO CREP',
    'LINO PANTALONERO RIGIDO', 'LINO PANTALONERO SPANDEX', 'MICROMORLEY BRITNEY',
    'MORLEY VISCOSA B FINO', 'MORLEY VISCOSA B MINI', 'PIQUE DE PUNTO', 'POLINEN',
    'POLINEN MELANGE', 'POLINEN RAYADO', 'POPLIN ESTAMPADO', 'RAYON LINO', 'RAYON TWILL',
    'RUSTICO NEVADO', 'RUSTICO VISCOSA', 'SIMIL LINO SPANDEX', 'TEJIDO CALI', 'TEJIDO MAUI',
    'TWILL LOLIS', 'TWILL LOLIS RAYADO', 'WAFFLE RAYADO',
  ],
  INVIERNO: [
    'CAMISACO', 'CAMISACO CON PIEL', 'CORDERITO BIFAZ', 'CORDERITO BIFAZ PRINT', 'CORDEROY',
    'CUERITO', 'CUERITO CROCO', 'CUERITO FRISADO', 'CUERITO VINTAGE', 'DARLON EMBOSS',
    'DARLON FOIL', 'DARLON PATAGONIA', 'DARLON PRINT', 'DARLON PUFF', 'FLANNEL LUMINOSO',
    'FRISA POLY', 'FRISA PREMIUM', 'FRISA VISCOSA', 'JACQUARD WINNIE', 'JERSEY CON PIEL',
    'LANILLA ABERCROMBIE', 'LANILLA ALASKA BRUSH', 'LANILLA ANGORA CALA', 'LANILLA ANGORA COSY',
    'LANILLA ANGORA LISA', 'LANILLA ANGORA LYON', 'LANILLA ANGORA TOWEL', 'LANILLA ASPEN',
    'LANILLA BRUSH LISA', 'LANILLA CASHMIRE', 'LANILLA CASHMIRE BRUSH PRINT',
    'LANILLA JAQUARD BRUSH', 'LANILLA LONDRES MORLEY', 'LANILLA MELLOW', 'LANILLA MILAN',
    'LANILLA PARIS', 'LANILLA SWEATER', 'LANILLA WAFFLE BRUSH', 'LANILLA WAFFLE MINI BRUSH',
    'MODAL ESTAMPADO KIDS', 'MODAL SOFT LUMINOSO', 'MODAL VISCOSA', 'MORLEY BRUSH PRINT',
    'MORLEY DIESEL BRUSHED', 'MORLEY FRISADO', 'MORLEY VINTAGE BRUSH', 'PAÑO BOUCLE ESTAMPADO',
    'PAÑO BOUCLE LISO', 'PAÑO BRUSH MELANGE', 'PAÑO CUADRILLE', 'PAÑO DE PUNTO', 'PAÑO LISO',
    'PATAGONIA', 'PLUSH DOBLE', 'PUNTO ROMA', 'RETRO FRIZADO', 'RUSTICO SUEDE', 'SARA KEY',
    'SCUBA SUEDE', 'SCUBA SUEDE CON CORDERITO', 'SOFT SHELL', 'TERMOPOLAR AGATA', 'TERMOPOLAR JQD',
    'TERMOPOLAR LISO', 'TERMOPOLAR MELANGE', 'TERMOPOLAR MORLEY', 'TERMOPOLAR RAYADO',
    'TIMBERLAND LISO', 'TIMBERLAND PRINT', 'TRENCH (WATERPROOF)', 'WAFFLE PLUSH',
  ],
  ATEMPORAL: [
    '4 WAYS', 'ALGODON CON LYCRA IMPORTADO', 'ANGIE GLITTER', 'BENGALINA CAMISERA',
    'BENGALINA ENGOMADA', 'BENGALINA METALIZADA', 'BENGALINA SATIN', 'BENGALINA DENIM',
    'BENGALINA LISA', 'BIZU BIZU', 'BIZU BIZU ACID', 'BIZU BIZU ANIMAL', 'BIZU BIZU COSMIC',
    'CHARO FOIL', 'CHARO STRASS', 'COTTON POPLIN SPX', 'CREP DE PUNTO', 'CREP ZARA', 'CUPRO',
    'DENIM JQD', 'DRY FIT', 'ENCAJE', 'GABARDINA ESMERILADA', 'GLITTER', 'JERSEY SET', 'LENTEJUELA',
    'LENTEJUELA PRINT', 'LENTEJUELA TAYLOR', 'MICRO MORLEY', 'MICROFIBRA CHARO',
    'MICROFIBRA ENGOMADA', 'MICROFIBRA LUCY', 'MICROFIBRA RIRI', 'MICROFIBRA VINTAGE',
    'MICROMORLEY ANGIE', 'MICROMORLEY FOIL', 'MICROMORLEY NICKY', 'MICROMORLEY RAYADO', 'MICROTUL',
    'MICROTUL (SOLO COLORES VERANO)', 'MICROTUL CON FLOCK', 'MICROTUL CON STRASS', 'MICROTUL FOIL',
    'MICROTUL LUREX', 'MODAL SOFT', 'MODAL SOFT PRINT', 'MODAL SOFT RAYADO', 'MORLEY CHER',
    'MORLEY DIESEL', 'MORLEY FOIL', 'MORLEY PRINT', 'MORLEY SOFT',
    'MORLEY VISCOSA (ANCHO, FINO, SIENA)', 'PANAL DE ABEJA', 'PANTALONERO BALI',
    'PANTALONERO CELINE', 'PANTALONERO KIM', 'PARACHUTTE', 'PARACHUTTE METALIZADO', 'PEGASUS',
    'POPLIN LISO', 'POPLIN RAYON CON LYCRA', 'PRADA', 'PUNTO LUREX', 'RED', 'RED FOIL', 'RIBB GIGI',
    'RIBB ONIX', 'SASTRERO ATENAS', 'SASTRERO MEGAN', 'SASTRERO MELANGE', 'SASTRERO MONACO',
    'SASTRERO TIM', 'SATEN CON SPANDEX (PLANO)', 'SATEN DE PUNTO', 'SCUBA CREPPE', 'SCUBA HILTON',
    'SCUBA YOGA', 'SEDITA EMILIA', 'SIMIL DENIM', 'TORY',
  ],
};

export const TEMPORADAS_BASE: readonly EntradaTemporada[] = (Object.keys(porTemporada) as Temporada[]).flatMap(
  (temporada) => porTemporada[temporada].map((nombre) => ({ nombre, temporada })),
);
